# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  delete:
    branches:
      - DisaPadla-patch-1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      username:
        description: 'Github Username'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['16']
        os: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v6
        if: ${{ github.event_name == 'delete' && github.event.ref_type == 'branch' }}
        with:
          script: |
            console.log(context);
      - uses: actions/github-script@v6
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          script: |
            console.log(context);
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Retrieve secret
        env:
          SUPERSECRET: ${{ secrets.SUPERSECRET }}
        run: echo "$SUPERSECRET"
        
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      # Runs a set of commands using the runners shell
      - name: npm ci, test
        env:
          SUPERSECRET: ${{ secrets.SUPERSECRET }}
        if: ${{ env.SUPERSECRET == 'some' }}
        run: |
          npm ci
          npm run test
      - name: npm build
        if: ${{ success() }}
        run: npm run build
      
